# Generated by Django 5.2.9 on 2025-12-19 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('from_type', models.SmallIntegerField(choices=[(1, 'Wallet'), (2, 'User')])),
                ('to_type', models.SmallIntegerField(choices=[(1, 'Wallet'), (2, 'Phone')])),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_transactions', to='users.phonenumber')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_transactions', to=settings.AUTH_USER_MODEL)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transactions', to='transaction.wallet')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_transactions', to='transaction.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='tx_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_wallet', 'status'], name='tx_from_wallet_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_wallet', 'status'], name='tx_to_wallet_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_phone', 'status'], name='tx_to_phone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'updated_at'], name='tx_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_type', 1), ('from_user__isnull', True), ('from_wallet__isnull', False)), models.Q(('from_type', 2), ('from_user__isnull', False), ('from_wallet__isnull', True)), _connector='OR'), name='valid_source'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_phone__isnull', True), ('to_type', 1), ('to_wallet__isnull', False)), models.Q(('to_phone__isnull', False), ('to_type', 2), ('to_wallet__isnull', True)), _connector='OR'), name='valid_destination'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
    ]
